<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="Version" Id="{68325ea1-f41c-4a46-a2db-1bd204db869b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Version
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*
1.1.0.1:	Boido	010120

Added new versioning System.
To update the project version open the VersionLib and modify the parameters.

1.1.1.2:	Boido	010120

Deleted the var_io chaincontroller from FB_Chain.
ChainController must now be set with the help of the define method in FB_Chain.

2.0.0.3:	Boido	010120

Deleted the define method from FB_Chain.
Initialization of FB_Chain occurs through FB_init in FB_Chain

2.0.1.4:	Boido	020120

Version.txt replaced with Version PRG

2.0.2.5:	Boido	020120

VersionLib removed.

3.0.0.6:	Boido	020120

FB_init removed from FB_Chain.

3.0.1.7:	Boido 	040120

Removed callAfterInit method from FB_Chain
Check for null reference in FB_Chain

3.0.2.8:	Boido 	050120

E_ChainStateMachine deleted.
*)]]></ST>
    </Implementation>
    <LineIds Name="Version">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="12" />
      <LineId Id="7" Count="0" />
      <LineId Id="23" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="25" Count="0" />
      <LineId Id="24" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="29" Count="0" />
      <LineId Id="37" Count="2" />
      <LineId Id="36" Count="0" />
      <LineId Id="44" Count="0" />
      <LineId Id="43" Count="0" />
      <LineId Id="46" Count="0" />
      <LineId Id="45" Count="0" />
      <LineId Id="47" Count="0" />
      <LineId Id="52" Count="2" />
      <LineId Id="51" Count="0" />
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>